version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    image: web:latest
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network

  tweet-service:
    container_name: tweet-service
    build:
      context: .
      dockerfile: ./apps/tweet-service/Dockerfile
    image: tweet-service:latest
    restart: always
    ports:
      - 3001:3001
    networks:
      - app_network

  user-service:
    container_name: user-service
    build:
      context: .
      dockerfile: ./apps/user-service/Dockerfile
    image: user-service:latest
    restart: always
    ports:
      - 3002:3002
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
