apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  DB_URL_USERL: bW9uZ29kYitzcnY6Ly9zdGFzc2lnOkxMeTlvZXRBMjMyM1ZPRllAa3dldHRlcmRiLmR2N213cXcubW9uZ29kYi5uZXQvVXNlcnM=
  DB_URL_TWEET: bW9uZ29kYitzcnY6Ly9zdGFzc2lnOkxMeTlvZXRBMjMyM1ZPRllAa3dldHRlcmRiLmR2N213cXcubW9uZ29kYi5uZXQvVHdlZXRz
