name: Publish to ACR

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      ACR_NAME: g3containerregistry
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      DOCKER_COMPOSE_FILE: docker-compose.yml
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build docker images
        run: |
          docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} build

      - name: Push Docker images to ACR
        run: |
          for image in $(docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} config --services); do
            docker tag $image ${{ env.ACR_NAME }}.azurecr.io/$image:$COMMIT_HASH
            docker push ${{ env.ACR_NAME }}.azurecr.io/$image:$COMMIT_HASH
          done
