name: Publish to ACR

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      ACR_NAME: g3containerregistry
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      APP_ENV: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker-compose.yml
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          tags: |
            ${{ env.ACR_NAME }}.azurecr.io/web:${{ github.sha }}
            ${{ env.ACR_NAME }}.azurecr.io/tweet-service:${{ github.sha }}
          # Add more tags for additional services if needed
