name: Publish to ACR

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      ACR_NAME: g3containerregistry
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      DOCKER_COMPOSE_FILE: docker-compose.yml
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Compose Services
        run: |
          docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} build
          docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} push

      - name: Push Docker images to ACR
        run: |
          for image in $(docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} config --services); do
            docker tag individualproject_$image ${{ env.ACR_NAME }}.azurecr.io/individualproject_$image:latest
            docker push ${{ env.ACR_NAME }}.azurecr.io/individualproject_$image:latest
          done
